// <auto-generated />
using System;
using DatabaseTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseTask.Data.Migrations
{
    [DbContext(typeof(DatabaseTaskBbContext))]
    [Migration("20251024133641_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseTask.Core.Domain.Child", b =>
                {
                    b.Property<Guid>("ChildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ChildAbsenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildGroupHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChildID");

                    b.HasIndex("ChildAbsenceId");

                    b.HasIndex("ChildGroupHistoryId");

                    b.HasIndex("QueueId");

                    b.ToTable("Child");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ChildAbsence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ChildAbsence");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ChildGroupHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("ChildGroupHistory");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<string>("MailAadress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChildAbsenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ChildGroupHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildAbsenceId");

                    b.HasIndex("ChildGroupHistoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MenuId");

                    b.HasIndex("QueueId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateFood")
                        .HasColumnType("date");

                    b.Property<string>("Dinner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DinnerSnack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lunch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Morning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MorningSnack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Portions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("RegDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Queue");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Child", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.ChildAbsence", null)
                        .WithMany("Child")
                        .HasForeignKey("ChildAbsenceId");

                    b.HasOne("DatabaseTask.Core.Domain.ChildGroupHistory", null)
                        .WithMany("Child")
                        .HasForeignKey("ChildGroupHistoryId");

                    b.HasOne("DatabaseTask.Core.Domain.Queue", null)
                        .WithMany("Child")
                        .HasForeignKey("QueueId");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Group", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.ChildAbsence", null)
                        .WithMany("Group")
                        .HasForeignKey("ChildAbsenceId");

                    b.HasOne("DatabaseTask.Core.Domain.ChildGroupHistory", null)
                        .WithMany("Group")
                        .HasForeignKey("ChildGroupHistoryId");

                    b.HasOne("DatabaseTask.Core.Domain.Employee", null)
                        .WithMany("Groups")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("DatabaseTask.Core.Domain.Menu", null)
                        .WithMany("Groups")
                        .HasForeignKey("MenuId");

                    b.HasOne("DatabaseTask.Core.Domain.Queue", null)
                        .WithMany("Group")
                        .HasForeignKey("QueueId");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Position", b =>
                {
                    b.HasOne("DatabaseTask.Core.Domain.Employee", null)
                        .WithMany("PositionName")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ChildAbsence", b =>
                {
                    b.Navigation("Child");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.ChildGroupHistory", b =>
                {
                    b.Navigation("Child");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Employee", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("PositionName");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Menu", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("DatabaseTask.Core.Domain.Queue", b =>
                {
                    b.Navigation("Child");

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
